### ISSUE TITLE
ELF file

### ISSUE THREAD

**Issue by sussyman04** [Nenkai/RRUnpacker#3]
Seems i don't have any .elf file in my folder. I am using the NPUB30457 version... anybody knows how should I proceed?

**Comment by Nenkai** [comment]
> Needs a decrypted main.self file to use alongside the RR7.DAT file.

**Comment by sussyman04** [comment]
I have the main.self file but of course the unpacker doesn't like it and gives it an error

**Comment by Megalith9** [comment]
Is there a solution? I've tried as well, yet I got an "Unhandled Exception". What's the issue? 
![image](https://github.com/Nenkai/RRUnpacker/assets/81762361/8badf23d-6de6-44ec-93c4-443ccd9f3124)

**Comment by Nenkai** [comment]
A decrypted self file is a elf file.
Decrypt it using RPCS3 or through any other means.
