### ISSUE TITLE
Crashed Upon Opening

### ISSUE THREAD

**Issue by NoahARKADE** [Nenkai/RRUnpacker#5]
im not sure if im using this right because i have my ridge racer 2 "RRP.dat" and crashes everytime i open the RRUnpacker.exe, like i said im not sure if im using it right so help is appreciated.

**Comment by Nenkai** [comment]
Make sure that your boot.bin file is decrypted beforehand. You can use PPSSPP to do so or DecEboot.

**Comment by NoahARKADE** [comment]
I have my boot.bin decrypted now, do i drag the boot.bin to the exe to open it or is that wrong?

**Comment by Nenkai** [comment]
The tool is a command line tool. The command prompt should be used, how to use it/usage should be shown when running it.

**Comment by NoahARKADE** [comment]
ah ok thanks
